import { StyleSheet } from 'react-native';
import { colors } from '../../settings/theme';
export const styles = StyleSheet.create({
  limitPresets: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  limitPreset: {
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: colors.surface,
  },
  limitPresetActive: { backgroundColor: colors.cyanSoft },
  limitPresetText: { color: colors.text },
  applicationAudioCard: {
    marginHorizontal: 14,
    marginBottom: 14,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: 'rgba(103,232,249,0.25)',
    borderRadius: 18,
    backgroundColor: colors.cyanSoft,
  },
  applicationAudioHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  applicationAudioCopy: { flex: 1 },
  applicationAudioControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  safeArea: { flex: 1, backgroundColor: colors.background },
  header: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  promptBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: 22,
    backgroundColor: 'rgba(0,0,0,0.65)',
  },
  promptCard: {
    gap: 12,
    padding: 20,
    borderRadius: 18,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalTitle: { color: colors.text, fontSize: 20, fontWeight: '800' },
  input: {
    color: colors.text,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 11,
    backgroundColor: colors.background,
  },
  submit: {
    alignItems: 'center',
    padding: 14,
    borderRadius: 12,
    backgroundColor: colors.cyan,
    marginTop: 8,
  },
  submitText: { color: '#082f49', fontWeight: '800' },
  clearPassword: { alignItems: 'center', padding: 12 },
  clearPasswordText: { color: colors.red, fontWeight: '700', fontSize: 12 },
  formError: { color: colors.red, fontSize: 12 },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  headerCopy: { flex: 1, minWidth: 0 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  headerAction: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.cyanSoft,
  },
  roomName: { color: colors.text, fontSize: 18, fontWeight: '700' },
  ownerName: { color: colors.textFaint, fontSize: 11, marginTop: 3 },
  mediaState: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  mediaConnected: { backgroundColor: colors.greenSoft },
  scrollContent: { paddingTop: 14 },
  roomScroll: { flex: 1 },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginHorizontal: 14,
    marginBottom: 10,
    padding: 11,
    borderWidth: 1,
    borderColor: 'rgba(248,113,113,0.2)',
    borderRadius: 13,
    backgroundColor: colors.redSoft,
  },
  errorText: { flex: 1, color: colors.red, fontSize: 11, lineHeight: 16 },
  screenStage: {
    position: 'relative',
    aspectRatio: 16 / 9,
    marginHorizontal: 14,
    marginBottom: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    backgroundColor: '#020203',
  },
  ownScreenCard: {
    marginHorizontal: 14,
    marginBottom: 14,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  ownScreenCopy: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  ownScreenText: { flex: 1, minWidth: 0, gap: 5 },
  startShareButton: {
    minWidth: 62,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(103,232,249,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  startShareText: { color: colors.cyan, fontSize: 14, fontWeight: '700' },
  stopShareButton: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(248,113,113,0.10)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    gap: 6,
  },
  stopShareText: { color: colors.red, fontSize: 14, fontWeight: '700' },
  screenShareOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  screenPrivacyNote: { flexDirection: 'row', gap: 12, paddingVertical: 12 },
  screenPrivacyText: {
    flex: 1,
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 21,
  },
  screenEmpty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  screenEmptyIcon: {
    width: 58,
    height: 58,
    marginBottom: 12,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.045)',
  },
  screenEmptyTitle: { color: colors.text, fontSize: 14, fontWeight: '700' },
  screenEmptyText: {
    color: colors.textFaint,
    fontSize: 11,
    lineHeight: 16,
    textAlign: 'center',
    marginTop: 7,
  },
  shareAvailable: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    backgroundColor: 'rgba(34,211,238,0.07)',
  },
  shareAvailableIcon: {
    width: 54,
    height: 54,
    marginBottom: 9,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#a5f3fc',
  },
  shareAvailableTitle: { color: colors.text, fontSize: 14, fontWeight: '800' },
  shareAvailableText: { marginTop: 4, color: colors.textFaint, fontSize: 10 },
  shareChoices: { paddingTop: 10, gap: 7 },
  watchButton: {
    maxWidth: 150,
    minWidth: 108,
    height: 38,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 13,
    backgroundColor: '#cffafe',
  },
  watchButtonText: { color: '#082f49', fontSize: 13, fontWeight: '800' },
  screenOverlay: {
    position: 'absolute',
    right: 9,
    bottom: 9,
    left: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sharer: {
    maxWidth: '75%',
    color: colors.text,
    fontSize: 10,
    paddingHorizontal: 9,
    paddingVertical: 7,
    overflow: 'hidden',
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.72)',
  },
  expandButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.72)',
  },
  screenActions: { flexDirection: 'row', gap: 7 },
  screenVolumeCard: {
    minHeight: 48,
    marginHorizontal: 14,
    marginTop: -5,
    marginBottom: 14,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 15,
    backgroundColor: colors.surface,
  },
  screenVolumeLabel: {
    flex: 1,
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  screenVolumeValue: {
    width: 40,
    color: colors.text,
    fontSize: 11,
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
  },
  volumeIconButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  volumeSlider: { flex: 1, height: 32, justifyContent: 'center' },
  volumeSliderRail: {
    position: 'absolute',
    right: 0,
    left: 0,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.13)',
  },
  volumeSliderFill: {
    position: 'absolute',
    left: 0,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.cyan,
  },
  volumeSliderThumb: {
    position: 'absolute',
    width: 15,
    height: 15,
    marginLeft: -7.5,
    borderWidth: 2,
    borderColor: '#ecfeff',
    borderRadius: 8,
    backgroundColor: colors.cyan,
  },
  shareSwitcher: { paddingHorizontal: 14, paddingBottom: 12, gap: 7 },
  shareSwitchButton: {
    maxWidth: 150,
    height: 36,
    paddingHorizontal: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  shareSwitchButtonActive: {
    borderColor: 'rgba(103,232,249,0.38)',
    backgroundColor: '#a5f3fc',
  },
  shareSwitchText: {
    maxWidth: 108,
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  shareSwitchTextActive: { color: '#083344' },
  memberCard: {
    marginHorizontal: 14,
    marginBottom: 12,
    padding: 15,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 19,
    backgroundColor: colors.surface,
  },
  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    marginBottom: 12,
  },
  sectionIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.cyanSoft,
  },
  sectionTitle: { color: colors.text, fontSize: 15, fontWeight: '700' },
  sectionSubtitle: { color: colors.textFaint, fontSize: 10, marginTop: 4 },
  memberList: { gap: 8 },
  memberChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingVertical: 7,
    paddingLeft: 7,
    paddingRight: 9,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'rgba(255,255,255,0.035)',
  },
  memberName: { color: 'rgba(244,244,245,0.7)', fontSize: 11 },
  memberUsername: { marginTop: 2, color: colors.textFaint, fontSize: 8 },
  voiceControls: {
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.borderStrong,
    backgroundColor: 'rgba(12,12,15,0.98)',
  },
  joinVoice: {
    flex: 1,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    borderRadius: 15,
    backgroundColor: '#ecfeff',
  },
  joinVoiceText: { color: '#164e63', fontSize: 15, fontWeight: '800' },
  controlDisabled: { opacity: 0.35 },
  micControl: {
    flex: 1,
    minWidth: 0,
    minHeight: 50,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    borderRadius: 15,
    backgroundColor: colors.greenSoft,
  },
  micMuted: { backgroundColor: colors.amberSoft },
  forceMuted: { backgroundColor: colors.redSoft },
  micText: {
    flexShrink: 1,
    color: colors.green,
    fontSize: 14,
    fontWeight: '700',
  },
  micMutedText: { color: colors.amber },
  forceMutedText: { color: colors.red },
  leaveControl: {
    width: 52,
    height: 50,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.redSoft,
  },
  audioSettingsContent: { padding: 16, gap: 16 },
  audioSettingsSection: {
    padding: 14,
    gap: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  noiseHint: { color: colors.textMuted, fontSize: 12, lineHeight: 18 },
  deviceSectionTitle: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 6,
  },
  noiseOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.border,
  },
  noiseOptionActive: {
    borderColor: colors.cyan,
    backgroundColor: colors.cyanSoft,
  },
  noiseOptionText: {
    flex: 1,
    marginRight: 10,
    color: colors.text,
    fontSize: 15,
    fontWeight: '600',
  },
  noiseOptionTextActive: { color: colors.cyan },
  noiseOptionTextDisabled: { color: colors.textMuted },
  fullscreen: { flex: 1, backgroundColor: '#000' },
  closeFullscreen: {
    position: 'absolute',
    top: 18,
    right: 18,
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  toolModal: { flex: 1, backgroundColor: colors.background },
  toolHeader: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  toolHeaderIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.cyanSoft,
  },
  toolTitle: { color: colors.text, fontSize: 17, fontWeight: '800' },
  toolSubtitle: { marginTop: 3, color: colors.textFaint, fontSize: 10 },
  toolContent: { paddingTop: 14, paddingBottom: 28 },
});
